export type CcTable = Record<string, number>

// INPUT CHANNEL PARAMETERS : sent to channels 1 - 9
export const input_channel_params: CcTable = {
  fader: 1,
  mute: 2,
  'eq-bypass': 3,
  'eq-high-boost': 4,
  'eq-high-frequency': 5,
  'eq-mid-boost': 6,
  'eq-mid-frequency': 7,
  'eq-mid-q': 8,
  'eq-low-boost': 9,
  'eq-low-frequency': 10,
  'gate-bypass': 11,
  'gate-threshold': 12,
  'gate-attack-time': 13,
  'gate-release-time': 14,
  'gate-gain-reduction': 15,
  'compressor-bypass': 16,
  'compressor-threshold': 17,
  'compressor-attack-time': 18,
  'compressor-release-time': 19,
  'compressor-ratio': 20,
  'compressor-makeup-gain': 21,
  'pan-main': 22,
  'send-aux-1': 23,
  'pan-aux-1': 24,
  'send-aux-2': 25,
  'pan-aux-2': 26,
  'send-aux-3': 27,
  'pan-aux-3': 28,
  trim: 29,
}

// MAIN OUTPUT BUS PARAMETERS : sent to channel 9
export const main_output_bus_params: CcTable = {
  fader: 1,
  mute: 2,
  'eq-bypass': 3,
  'eq-high-boost': 4,
  'eq-high-frequency': 5,
  'eq-mid-boost': 6,
  'eq-mid-frequency': 7,
  'eq-mid-q': 8,
  'eq-low-boost': 9,
  'eq-low-frequency': 10,
  'gate-bypass': 11,
  'gate-threshold': 12,
  'gate-attack-time': 13,
  'gate-release-time': 14,
  'gate-gain-reduction': 15,
  'compressor-bypass': 16,
  'compressor-threshold': 17,
  'compressor-attack-time': 18,
  'compressor-release-time': 19,
  'compressor-ratio': 20,
  'compressor-makeup-gain': 21,
}

// MISC. PARAMETERS (REVERB/SURROUND/AUXES) : sent to channel 10
export const misc_params: CcTable = {
  'reverb-send-1': 1,
  'reverb-send-2': 2,
  'reverb-send-3': 3,
  'reverb-send-4': 4,
  'reverb-send-5': 5,
  'reverb-send-6': 6,
  'reverb-send-7': 7,
  'reverb-send-8': 8,
  'reverb-predelay': 9,
  'reverb-decay-time': 10,
  'reverb-damping': 11,
  'reverb-diffusion': 12,
  'reverb-level': 13,
  'reverb-bypass': 14,
  'surround-panner-1-x': 15,
  'surround-panner-1-y': 16,
  'surround-panner-2-x': 17,
  'surround-panner-2-y': 18,
  'surround-panner-3-x': 19,
  'surround-panner-3-y': 20,
  'surround-panner-4-x': 21,
  'surround-panner-4-y': 22,
  'aux-1-out': 23,
  'aux-1-mute': 24,
  'aux-2-out': 25,
  'aux-2-mute': 26,
  'aux-3-out': 27,
  'aux-3-mute': 28,
}

/** Indexed [input, main, misc] — order matters; consumed by control-messages and help. */
export const messages: CcTable[] = [input_channel_params, main_output_bus_params, misc_params]
